stages:          # List of stages for jobs, and their order of execution
  - build

build-package:
  stage: build
  image: python:3.10
  only:
    - main
  script:
    - cat $PYPIRC > /tmp/.pypirc
    - pip install twine
    - pip install -r requirements.txt
    - python setup.py  bdist_wheel
    - python -m twine upload --repository testpypi dist/* --config-file /tmp/.pypirc
